# Generated by Django 6.1 on 2026-09-30 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0035_message_panels"),
        ("tenants", "0176_relock_after_profile_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeWriteEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("journal_doc", "Journal Doc"),
                            ("fuel", "Fuel"),
                            ("horizons_goal", "Horizons Goal"),
                            ("calendar", "Calendar"),
                        ],
                        max_length=24,
                    ),
                ),
                ("ref", models.JSONField(default=dict)),
                ("verb", models.CharField(choices=[("created", "Created"), ("updated", "Updated")], max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runtime_write_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "runtime_write_events",
                "indexes": [
                    models.Index(fields=["tenant", "-created_at"], name="rwe_tenant_created_idx"),
                    models.Index(fields=["created_at"], name="rwe_created_idx"),
                ],
            },
        ),
    ]
