# Generated by Django 6.0.7 on 2026-10-05 04:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_delete_yardtalklicense"),
        ("tenants", "0179_tenant_stripe_subscription_ended_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppStoreNotification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notification_uuid", models.CharField(max_length=64, unique=True)),
                ("notification_type", models.CharField(max_length=48)),
                ("subtype", models.CharField(blank=True, default="", max_length=48)),
                ("environment", models.CharField(blank=True, default="", max_length=16)),
                ("original_transaction_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("signed_date", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, default="", max_length=32)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "app_store_notifications",
            },
        ),
        migrations.CreateModel(
            name="AppStoreSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("original_transaction_id", models.CharField(max_length=64, unique=True)),
                ("product_id", models.CharField(blank=True, default="", max_length=128)),
                ("environment", models.CharField(blank=True, default="", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("grace", "In billing grace period"),
                            ("billing_retry", "Billing retry (not entitled)"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("entitles", models.BooleanField(db_default=False, default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(blank=True, null=True)),
                ("app_account_token", models.UUIDField(blank=True, null=True)),
                ("signed_date", models.DateTimeField(blank=True, null=True)),
                ("bound_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_store_subscriptions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "app_store_subscriptions",
                "indexes": [models.Index(fields=["tenant", "entitles"], name="app_store_s_tenant__313010_idx")],
            },
        ),
    ]
