# Generated by Django 6.0.7 on 2026-09-28 03:07

from django.db import migrations

RELOCK_SQL = r"""
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT schemaname, tablename
    FROM pg_tables
    WHERE schemaname = 'public'
      AND tableowner = current_user
      AND rowsecurity = false
  LOOP
    EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY',
                   r.schemaname, r.tablename);
  END LOOP;
END
$$;
"""

REVERSE_SQL = "-- Reversing would leave public tables unlocked at migration time. Do not auto-reverse."


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0015_projects_v2_rls_backstop"),
        ("tenants", "0171_openclaw_auto_upgrade"),
    ]

    operations = [migrations.RunSQL(RELOCK_SQL, REVERSE_SQL)]
