# Generated by Django 6.0.7 on 2026-09-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0174_relock_after_projects_v2_assistant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="image_refresh_blocked_tag",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OpenClaw image tag whose wake-time refresh failed its health check and was reverted; the wake path will not try this tag again",
                max_length=255,
            ),
        ),
    ]
