# Generated by Django 6.0.7 on 2026-10-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0178_relock_after_projects_people_care"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="stripe_subscription_ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
