# Generated by Django 6.0.7 on 2026-10-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0180_relock_after_app_store_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="image_plugin_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Plugin dirs the running OpenClaw image reported at its last boot (container-started hook)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="image_plugins_tag",
            field=models.CharField(
                blank=True,
                default="",
                help_text="container_image_tag that image_plugin_ids was reported under; a mismatch means unknown",
                max_length=255,
            ),
        ),
    ]
