# Generated by Django 6.0.7 on 2026-09-28 03:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0012_dedupe_pending_shares"),
        ("journal", "0031_journalentry_energy_score"),
        ("tenants", "0171_openclaw_auto_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedgoalmembership",
            name="muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sharedgoalupdate",
            name="kind",
            field=models.CharField(
                choices=[
                    ("joined", "Joined"),
                    ("step_added", "Step added"),
                    ("step_assigned", "Step assigned"),
                    ("step_answered", "Step answered"),
                    ("step_done", "Step done"),
                    ("step_unblocked", "Step unblocked"),
                    ("milestone_reached", "Milestone reached"),
                    ("task_added", "Task added"),
                    ("task_completed", "Task completed"),
                    ("milestone", "Milestone"),
                    ("note", "Note"),
                    ("progress", "Progress"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="SharedGoalMilestone",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("reached_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "shared_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="milestones", to="friends.sharedgoal"
                    ),
                ),
            ],
            options={
                "db_table": "shared_goal_milestones",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SharedGoalStep",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="steps",
                        to="friends.sharedgoalmilestone",
                    ),
                ),
                (
                    "shared_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="friends.sharedgoal"
                    ),
                ),
            ],
            options={
                "db_table": "shared_goal_steps",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SharedGoalStepAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("asked", "Asked"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("countered", "Countered"),
                        ],
                        default="asked",
                        max_length=10,
                    ),
                ),
                ("counter_start", models.DateField(blank=True, null=True)),
                ("counter_due", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_assignments",
                        to="friends.sharedgoalmembership",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="friends.sharedgoalstep",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="journal.task",
                    ),
                ),
            ],
            options={
                "db_table": "shared_goal_step_assignments",
                "constraints": [models.UniqueConstraint(fields=("step", "membership"), name="uq_goal_step_member")],
            },
        ),
        migrations.CreateModel(
            name="SharedGoalStepDependency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_dependencies",
                        to="friends.sharedgoalstep",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_dependencies",
                        to="friends.sharedgoalstep",
                    ),
                ),
            ],
            options={
                "db_table": "shared_goal_step_dependencies",
                "constraints": [
                    models.UniqueConstraint(fields=("blocker", "blocked"), name="uq_goal_step_dependency"),
                    models.CheckConstraint(
                        condition=models.Q(("blocker", models.F("blocked")), _negated=True),
                        name="goal_step_no_self_dependency",
                    ),
                ],
            },
        ),
    ]
