# Generated by Django 6.0.7 on 2026-09-28 03:07

from django.db import migrations


# Frozen migration-only normalization; never import evolving application code.
def _clean(value, limit):
    import unicodedata

    text = "".join(
        " " if c.isspace() else c
        for c in str(value or "")
        if c.isspace() or unicodedata.category(c) not in {"Cc", "Cf", "Cs"}
    )
    return " ".join(text.split())[:limit]


def backfill(apps, schema_editor):
    Update = apps.get_model("friends", "SharedGoalUpdate")
    Membership = apps.get_model("friends", "SharedGoalMembership")
    Step = apps.get_model("friends", "SharedGoalStep")
    Assignment = apps.get_model("friends", "SharedGoalStepAssignment")
    Task = apps.get_model("journal", "Task")
    db = schema_editor.connection.alias
    from uuid import UUID

    # Exact projection._next_step rule: payload title, stripped + lowercased,
    # same member, regardless of update chronology (legacy behavior).
    completed = {}
    for row in Update.objects.using(db).filter(kind="task_completed").order_by("created_at"):
        key = (row.shared_goal_id, row.tenant_id, (row.payload or {}).get("title", "").strip().lower())
        completed[key] = row.created_at
    for row in Update.objects.using(db).filter(kind="task_added").order_by("created_at", "id"):
        payload = row.payload or {}
        title = payload.get("title") or row.text or ""
        stamp = completed.get((row.shared_goal_id, row.tenant_id, title.strip().lower()))
        step, _ = Step.objects.using(db).get_or_create(
            id=row.id,
            defaults={
                "shared_goal_id": row.shared_goal_id,
                "title": _clean(title, 120) or "Next step",
                "status": "done" if stamp else "open",
                "completed_at": stamp,
                "completed_by_id": row.tenant_id if stamp else None,
                "created_by_id": row.tenant_id,
            },
        )
        member = Membership.objects.using(db).filter(shared_goal_id=row.shared_goal_id, tenant_id=row.tenant_id).first()
        if member is None:
            continue  # Preserve the step even if its historical membership was removed.
        task_id = None
        try:
            raw_id = UUID(str(payload.get("task_id")))
            task_id = (
                Task.objects.using(db).filter(id=raw_id, tenant_id=row.tenant_id).values_list("id", flat=True).first()
            )
        except (ValueError, TypeError):
            pass
        Assignment.objects.using(db).get_or_create(
            step=step,
            membership=member,
            defaults={
                "status": "accepted",
                "task_id": task_id,
                "asked_by_id": row.tenant_id,
                "responded_at": row.created_at,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0013_projects_v2_core"),
    ]

    operations = [migrations.RunPython(backfill, migrations.RunPython.noop)]
