# Generated by Django 6.0.7 on 2026-09-28 03:07

from django.db import migrations

# Same FORCE-RLS/named-role/permissive-write backstop as 0008/0011.
# Nonrecursive: assignments/edges -> steps -> existing membership table.
TABLE_GOAL = {
    "shared_goal_milestones": "shared_goal_id",
    "shared_goal_steps": "shared_goal_id",
    "shared_goal_step_assignments": "(SELECT s.shared_goal_id FROM shared_goal_steps s WHERE s.id = step_id)",
    "shared_goal_step_dependencies": "(SELECT s.shared_goal_id FROM shared_goal_steps s WHERE s.id = blocker_id)",
}
TENANT = "nullif(current_setting('app.tenant_id', true), '')::uuid"
SERVICE = "coalesce(current_setting('app.service_role', true), '') = 'true'"
APPLY_SQL = """
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user NOLOGIN;
  END IF;
END $$;
"""
REVERSE_SQL = ""
for table, goal in TABLE_GOAL.items():
    # Qualify shared_goal_id: otherwise the correlated membership subquery
    # resolves it to its own column and accidentally grants every project.
    goal = f"{table}.{goal}" if goal == "shared_goal_id" else goal
    APPLY_SQL += f"""
ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {table} FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS friends_{table}_sel ON {table};
CREATE POLICY friends_{table}_sel ON {table} FOR SELECT TO app_user USING (
 {SERVICE} OR EXISTS (SELECT 1 FROM shared_goal_memberships m
 WHERE m.shared_goal_id = {goal} AND m.tenant_id = {TENANT} AND m.status = 'active')
);
DROP POLICY IF EXISTS friends_{table}_ins ON {table};
CREATE POLICY friends_{table}_ins ON {table} FOR INSERT TO app_user WITH CHECK (true);
DROP POLICY IF EXISTS friends_{table}_upd ON {table};
CREATE POLICY friends_{table}_upd ON {table} FOR UPDATE TO app_user USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS friends_{table}_del ON {table};
CREATE POLICY friends_{table}_del ON {table} FOR DELETE TO app_user USING (true);
"""
    for suffix in ("sel", "ins", "upd", "del"):
        REVERSE_SQL += f"DROP POLICY IF EXISTS friends_{table}_{suffix} ON {table};\n"
    REVERSE_SQL += f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;\n"


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0014_projects_v2_backfill"),
    ]

    operations = [migrations.RunSQL(APPLY_SQL, REVERSE_SQL)]
