# Generated by Django 6.0.7 on 2026-09-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0015_projects_v2_rls_backstop"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedgoalmembership",
            name="linked_goal_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharedgoalstepassignment",
            name="asked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharedgoalstepassignment",
            name="due_nudged_for",
            field=models.DateField(blank=True, null=True),
        ),
    ]
