# Generated by Django 6.0.7 on 2026-09-28 07:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0016_projects_v2_notify_goal_link"),
        ("tenants", "0173_relock_after_projects_v2_notify"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingProjectAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("partial", "Partly applied"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("from_tainted_turn", models.BooleanField(default=False)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shared_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="friends.sharedgoal"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_project_actions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "friends_pending_project_actions",
                "indexes": [models.Index(fields=["tenant", "status"], name="friends_pen_tenant__348b72_idx")],
            },
        ),
        migrations.CreateModel(
            name="ProjectDraft",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payload", models.JSONField(default=dict)),
                ("source", models.CharField(default="chat", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "published_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="friends.sharedgoal",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="project_drafts", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "friends_project_drafts",
                "indexes": [models.Index(fields=["tenant", "created_at"], name="friends_pro_tenant__f6e865_idx")],
            },
        ),
    ]
