# Generated by Django 6.0.7 on 2026-09-29 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0017_projects_v2_drafts_proposals"),
    ]

    operations = [
        migrations.CreateModel(
            name="NeighborPhoto",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="photo",
                        serialize=False,
                        to="friends.neighborprofile",
                    ),
                ),
                ("image", models.BinaryField()),
                ("content_type", models.CharField(default="image/jpeg", max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "neighbor_photos",
            },
        ),
        migrations.AddField(
            model_name="contentreport",
            name="photo_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="friends.neighborprofile",
            ),
        ),
        migrations.AddField(
            model_name="neighborprofile",
            name="photo_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentreport",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("shared_lesson", "Shared spark"),
                    ("friend_message", "Chat"),
                    ("general", "General / support"),
                    ("profile_photo", "Profile photo"),
                ],
                max_length=16,
            ),
        ),
    ]
