# Generated by Django 6.0.7 on 2026-10-02 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0018_profile_photos"),
        ("tenants", "0177_relock_after_runtime_write_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedgoalstep",
            name="done_link",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sharedgoalstep",
            name="done_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sharedgoalstep",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sharedgoalstep",
            name="review_set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="sharedgoalstep",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharedgoalstep",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="sharedgoalstepassignment",
            name="kept_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharedgoalstepassignment",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharedgoalstepassignment",
            name="still_yours_nudged_for",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sharedgoalstepassignment",
            name="suggested_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="friends.sharedgoalmembership",
            ),
        ),
        migrations.AlterField(
            model_name="sharedgoalstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In progress"),
                    ("in_review", "Waiting for a look"),
                    ("done", "Done"),
                    ("skipped", "Skipped"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="sharedgoalstepassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("asked", "Asked"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("countered", "Countered"),
                    ("released", "Released"),
                ],
                default="asked",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sharedgoalupdate",
            name="kind",
            field=models.CharField(
                choices=[
                    ("joined", "Joined"),
                    ("step_added", "Step added"),
                    ("step_assigned", "Step assigned"),
                    ("step_answered", "Step answered"),
                    ("step_done", "Step done"),
                    ("step_unblocked", "Step unblocked"),
                    ("step_released", "Step released"),
                    ("step_submitted", "Step waiting for a look"),
                    ("step_questioned", "Step questioned"),
                    ("member_left", "Member left"),
                    ("owner_changed", "Owner changed"),
                    ("milestone_reached", "Milestone reached"),
                    ("task_added", "Task added"),
                    ("task_completed", "Task completed"),
                    ("milestone", "Milestone"),
                    ("note", "Note"),
                    ("progress", "Progress"),
                ],
                max_length=24,
            ),
        ),
    ]
